### ISSUE TITLE
Clarify if crate is utf-8 compliant.

### ISSUE THREAD

**Issue by nilscript** [bluss/scratchspace#14]
I hope I'm wrong about this but does one not need to iterate over characters instead of bytes when searching for a pattern?
I have a feeling that false positives might pop up if you treat a string as a byte sequence.

I got my suspicions after seeing this function:
```rust
pub fn find_str(text: &str, pattern: &str) -> Option<usize> {
    find_bytes(text.as_bytes(), pattern.as_bytes())
}
```

Can you clarify it in the documentation and the readme?

**Comment by bluss** [comment]
Yes utf 8 code sequences don't overlap in that way so if you search for utf8 (str), you get the right result. This was part of the utf8 design luckily. Same approach with search here as in as in libstd.

**Comment by nilscript** [comment]
Thanks for the clarification!
